# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.define "lamp" do |lamp|
    # accessing "localhost:9080" will access port 80 on the guest machine.
#    lamp.vm.network "forwarded_port", guest: 80, host: 9080
#    lamp.vm.network "forwarded_port", guest: 3306, host: 3306
    lamp.vm.network "private_network", ip: "192.168.30.10"

    # Ports required for CAS role
#    lamp.vm.network "forwarded_port", guest: 8080, host: 8080
#    lamp.vm.network "forwarded_port", guest: 8443, host: 8443
    lamp.vm.hostname="lamp"
    lamp.vm.synced_folder "share", "/share"

# Annoying hack for bare bones ubuntu (no python installed)
#    lamp.vm.provision "shell" do |sh|
#      sh.inline = "apt-get install -y python"
#    end

    lamp.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/standalone.yml"
    end
  end
end
