# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # As this is a dev setup, don't specify keys per box
  config.ssh.insert_key = false 

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 8080, host: 8080
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.hostname "web"
    web.vm.synced_folder "share", "/share"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/web.yml"
    end
  end

  config.vm.define "db" do |db|
    db.vm.network "forwarded_port", guest: 3306, host: 3306
    db.vm.network "private_network", ip: "192.168.33.11"
    db.vm.hostname "db"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/db.yml"
    end
  end

end
