# Provision root permissions for the MariaDB Server
  - name: Remove OLD ISPyB database tables
    mysql_db:
      name: "{{ item }}"
      state: absent
    with_items:
      -  pydb
      -  pyconfig

  - name: Create ISPyB database table
    mysql_db:
      name: "{{ ispyb_db_name }}"
      state: present

  - name: Setup ISPyB admin users
    mysql_user:
      name: "{{ispyb_db_user}}"
      password: "{{ ispyb_db_password }}"
      state: present
      host: '%'
      priv: '{{ ispyb_db_name }}.*:ALL'

  - name: Reload Privilege Tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

  - name: Checkout ispyb-database tables, routines, and sample data
    git:
      repo: https://github.com/DiamondLightSource/ispyb-database
      dest: /opt/ispyb-database
    ignore_errors: False

  - name: Import ISPyB tables, routines, and sample data
    mysql_db:
      state: import
      name: ispyb
      target: "{{ item }}"
    with_items:
      - /opt/ispyb-database/schema/tables.sql
      - /opt/ispyb-database/schema/routines.sql
      - /opt/ispyb-database/schema/data.sql
    ignore_errors: False
