alter table BeamLineSetup 
  drop DETECTORTYPE,
  drop DETECTORMANUFACTURER,
  drop DETECTORMODEL,
  drop DETECTORPIXELSIZEHORIZONTAL,
  drop DETECTORPIXELSIZEVERTICAL,
  drop DETECTORMAXRESOLUTION,
  drop DETECTORMINRESOLUTION;