ALTER TABLE Container DROP FOREIGN KEY IF EXISTS Container_ibfk6;
ALTER TABLE Container DROP FOREIGN KEY IF EXISTS BLSession_ibfk_3;
ALTER TABLE Container ADD CONSTRAINT Container_ibfk6 FOREIGN KEY (sessionId) REFERENCES BLSession (sessionId) ON DELETE SET NULL ON UPDATE CASCADE;